services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  mongo-init-replica:
    image: mongo:6.0
    depends_on: [mongo]
    entrypoint: ["bash", "-c", "sleep 3 && mongosh --host mongo:27017 --eval 'rs.initiate({_id:\"rs0\", members:[{_id:0, host:\"mongo:27017\"}]})'"]

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # solo DEV
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports: ["9200:9200"]
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    depends_on: [es]
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports: ["5601:5601"]

  monstache:
    image: rwynn/monstache:6.7.7
    container_name: monstache
    depends_on: [mongo, es, mongo-init-replica]
    volumes:
      - ./monstache.toml:/monstache.toml
    command: ["-f", "/monstache.toml"]
  
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"        
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  api:
    build: ./api
    container_name: api
    depends_on:
      - mongo
      - es
      - mongo-init-replica
      - ollama
    environment:
      - MONGO_URL=mongodb://mongo:27017/appdb?replicaSet=rs0
      - ELASTIC_URL=http://es:9200
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama3.2
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  mongo_data:
  es_data:
  ollama_data:
